version: '3.8'

networks:
  kilogram:

services:
  nginx:
    image: nginx:stable
    container_name: kilogram_nginx
    volumes:
      - ./src:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8070:80"
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - kilogram
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9003:9000"
    container_name: kilogram_php
    networks:
      - kilogram

  mysql:
    image: "mariadb/server:10.3"
    container_name: kilogram_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_USER: hasnat
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: kilogram
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    ports:
      - "4304:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - kilogram

  composer:
    image: "composer:latest"
    container_name: lara_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - kilogram

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kilogram_artisan
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - kilogram
    entrypoint: ['/var/www/html/artisan']

  redis:
    image: redis:alpine
    container_name: kilogram_redis
    networks:
      - kilogram
    command: redis-server --appendonly yes --requirepass "123"
    volumes:
      - ./data/redis:/data
    ports:
      - "8002:6379"