version: '3.8'

networks:
  kilogram:

services:
  nginx:
    image: nginx:stable
    container_name: kilogram_nginx
    volumes:
      - ./src:/var/www/html:cached
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    networks:
      - kilogram
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9003:9000"
    container_name: kilogram_php
    networks:
      - kilogram

  mysql:
    image: "mariadb/server:10.3"
    container_name: kilogram_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_USER: hasnat
      MYSQL_PASSWORD: RWrHu4YXn4DBDsTc
      MYSQL_DATABASE: kilogram
      MYSQL_ROOT_PASSWORD: 7KeZ3yHCKEA75CWT
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    ports:
      - "4304:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - kilogram

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/html/certbot --email me@westsidecoders.net --agree-tos --no-eff-email -d kilogram.westsidecoders.net -d www.kilogram.westsidecoders.net
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot

  composer:
    image: "composer:latest"
    container_name: lara_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - kilogram

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kilogram_artisan
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - kilogram
    entrypoint: ['/var/www/html/artisan']

  redis:
    image: redis:alpine
    container_name: kilogram_redis
    networks:
      - kilogram
    command: redis-server --appendonly yes --requirepass "123"
    volumes:
      - ./data/redis:/data
    ports:
      - "8002:6379"